#!/bin/sh
#
# funcd    Fedora Unified Network Control
###################################

# LSB header

### BEGIN INIT INFO
# Provides: funcd
# Required-Start: network, xinetd, httpd
# Default-Start: 3 4 5
# Short-Description: Fedora Unified Network Control
# Description: Crazy simple, secure remote management.
### END INIT INFO

# chkconfig header

# chkconfig: 345 99 99 
# description:  Crazy simple, secure remote management.
#
# processname: /usr/bin/funcd

# Sanity checks.
[ -x /usr/bin/funcd ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

SERVICE=funcd
PROCESS=funcd
CONFIG_ARGS=" "

RETVAL=0

start() {
    echo -n $"Starting func daemon: "
    daemon --check $SERVICE $PROCESS --daemon $CONFIG_ARGS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
    return $RETVAL
}

stop() {
    echo -n $"Stopping func daemon: "
    killproc $PROCESS
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
	rm -f /var/lock/subsys/$SERVICE
        rm -f /var/run/$SERVICE.pid
    fi
}

restart() {
   stop
   start
}

# See how we were called.
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        status $PROCESS
        RETVAL=$?
        ;;
    condrestart)
        [ -f /var/lock/subsys/$SERVICE ] && restart || :
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        exit 1
        ;;
esac
exit $RETVAL

