#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'funcweb==0.1','console_scripts','start-funcweb'
__requires__ = 'funcweb==0.1'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('funcweb==0.1', 'console_scripts', 'start-funcweb')()
   )
