#!/usr/bin/python

import sys
import distutils.sysconfig

sys.path.append("%s/func" % distutils.sysconfig.get_python_lib())

import certmaster

cm = certmaster.CertMaster('/etc/func/certmaster.conf')
server = certmaster.serve(cm)

