#!/usr/bin/python

##
## Copyright 2007-2008, Red Hat Inc
## Michael DeHaan <mdehaan@redhat.com>
##
## This software may be freely redistributed under the terms of the GNU
## general public license.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


import sys
import distutils.sysconfig
import func.overlord.inventory as func_inventory

inventory = func_inventory.FuncInventory()
inventory.run(sys.argv)
