#!/usr/bin/python

import sys
import distutils.sysconfig

# sys.path.append("%s/func" % distutils.sysconfig.get_python_lib())

import func.overlord.func_command as func_command

myname, argv = sys.argv[0], sys.argv[1:]
cli = func_command.FuncCommandLine()
cli.parse(argv)


