#!/usr/bin/python


import sys
import distutils.sysconfig

sys.path.append("%s/func" % distutils.sysconfig.get_python_lib())

from minion import server

if __name__ == "__main__":
    server.main(sys.argv)
