#!/usr/bin/python

import sys
import distutils.sysconfig

# sys.path.append("%s/func" % distutils.sysconfig.get_python_lib())

import func.overlord.client as client

myname, argv = sys.argv[0], sys.argv[1:]
cli = client.FuncCommandLine(myname, argv)
cli.run()


